import { TaskEnum, TypeEnum } from "./enums";
import { Task } from "./tasks";

export const diaryTasks: Task[] = [
  {
    type: TypeEnum.diary,
    task: TaskEnum.ardougne_easy,
    requirements: [TaskEnum.thieving_level_5, TaskEnum.biohazard, TaskEnum.rune_mysteries],
  } as Task,
  {
    type: TypeEnum.diary,
    task: TaskEnum.ardougne_medium,
    requirements: [
      TaskEnum.ardougne_easy,
      TaskEnum.strength_level_40,
      TaskEnum.agility_level_40,
      TaskEnum.smithing_level_5,
      TaskEnum.ranged_level_25,
      TaskEnum.thieving_level_40,
      TaskEnum.crafting_level_52,
      TaskEnum.firemaking_level_52,
      TaskEnum.magic_level_52,
      TaskEnum.fletching_level_5,
      TaskEnum.woodcutting_level_40,
      TaskEnum.farming_level_35,
      TaskEnum.construction_level_10,
      TaskEnum.enlightened_journey, TaskEnum.the_hand_in_the_sand,
      TaskEnum.rune_mysteries, TaskEnum.tower_of_life, TaskEnum.underground_pass, TaskEnum.fairytale_ii_cure_a_queen, TaskEnum.sea_slug, TaskEnum.watchtower, TaskEnum.ardougne_easy
    ],
    questPointRequirement: 20
  } as Task,
  {
    type: TypeEnum.diary,
    task: TaskEnum.ardougne_hard,
    requirements: [
      TaskEnum.ardougne_medium,
      TaskEnum.mining_level_52,
      TaskEnum.strength_level_52,
      TaskEnum.agility_level_56,
      TaskEnum.smithing_level_69,
      TaskEnum.herblore_level_48,
      TaskEnum.fishing_level_56,
      TaskEnum.ranged_level_60,
      TaskEnum.thieving_level_72,
      TaskEnum.cooking_level_56,
      TaskEnum.prayer_level_44,
      TaskEnum.crafting_level_52,
      TaskEnum.firemaking_level_52,
      TaskEnum.magic_level_66,
      TaskEnum.fletching_level_10,
      TaskEnum.woodcutting_level_52,
      TaskEnum.runecraft_level_66,
      TaskEnum.farming_level_72,
      TaskEnum.construction_level_52,
      TaskEnum.hunter_level_60,
      TaskEnum.enlightened_journey, TaskEnum.the_hand_in_the_sand,
      TaskEnum.legends_quest, TaskEnum.monkey_madness_i, TaskEnum.mournings_end_part_ii, TaskEnum.rune_mysteries, TaskEnum.tower_of_life, TaskEnum.watchtower, TaskEnum.fairytale_ii_cure_a_queen, TaskEnum.sea_slug
    ],
    questPointRequirement: 107
  } as Task,
  {
    type: TypeEnum.diary,
    task: TaskEnum.ardougne_elite,
    requirements: [
      TaskEnum.ardougne_hard,
      TaskEnum.attack_level_5,
      TaskEnum.hitpoints_level_10,
      TaskEnum.mining_level_52,
      TaskEnum.strength_level_52,
      TaskEnum.agility_level_90,
      TaskEnum.smithing_level_91,
      TaskEnum.defence_level_5,
      TaskEnum.herblore_level_48,
      TaskEnum.fishing_level_81,
      TaskEnum.ranged_level_60,
      TaskEnum.thieving_level_83,
      TaskEnum.cooking_level_91,
      TaskEnum.prayer_level_44,
      TaskEnum.crafting_level_52,
      TaskEnum.firemaking_level_52,
      TaskEnum.magic_level_94,
      TaskEnum.fletching_level_69,
      TaskEnum.woodcutting_level_52,
      TaskEnum.runecraft_level_66,
      TaskEnum.slayer_level_5,
      TaskEnum.farming_level_85,
      TaskEnum.construction_level_52,
      TaskEnum.hunter_level_60,
      TaskEnum.sailing_level_5,
      TaskEnum.desert_treasure_i, TaskEnum.enlightened_journey, TaskEnum.the_hand_in_the_sand, TaskEnum.haunted_mine, TaskEnum.legends_quest, TaskEnum.monkey_madness_i, TaskEnum.mournings_end_part_ii,
      TaskEnum.rune_mysteries, TaskEnum.tower_of_life, TaskEnum.watchtower, TaskEnum.fairytale_ii_cure_a_queen, TaskEnum.sea_slug
    ],
    questPointRequirement: 107
  } as Task,

  {
    type: TypeEnum.diary,
    task: TaskEnum.desert_easy,
    requirements: [
      TaskEnum.thieving_level_25,
      TaskEnum.hunter_level_5,
      TaskEnum.icthlarins_little_helper
    ],
  } as Task,
  {
    type: TypeEnum.diary,
    task: TaskEnum.desert_medium,
    requirements: [
      TaskEnum.desert_easy,
      TaskEnum.mining_level_40,
      TaskEnum.agility_level_30,
      TaskEnum.herblore_level_40,
      TaskEnum.ranged_level_40,
      TaskEnum.thieving_level_40,
      TaskEnum.prayer_level_44,
      TaskEnum.crafting_level_52,
      TaskEnum.firemaking_level_48,
      TaskEnum.magic_level_40,
      TaskEnum.woodcutting_level_35,
      TaskEnum.slayer_level_25,
      TaskEnum.construction_level_20,
      TaskEnum.hunter_level_48,
      TaskEnum.eagles_peak, TaskEnum.enakhras_lament, TaskEnum.the_golem, TaskEnum.spirits_of_the_elid, TaskEnum.icthlarins_little_helper
    ],
  } as Task,
  {
    type: TypeEnum.diary,
    task: TaskEnum.desert_hard,
    requirements: [
      TaskEnum.desert_medium,
      TaskEnum.attack_level_52,
      TaskEnum.hitpoints_level_5,
      TaskEnum.mining_level_60,
      TaskEnum.strength_level_5,
      TaskEnum.agility_level_72,
      TaskEnum.smithing_level_69,
      TaskEnum.defence_level_40,
      TaskEnum.herblore_level_40,
      TaskEnum.fishing_level_5,
      TaskEnum.ranged_level_40,
      TaskEnum.thieving_level_66,
      TaskEnum.cooking_level_5,
      TaskEnum.prayer_level_44,
      TaskEnum.crafting_level_63,
      TaskEnum.firemaking_level_60,
      TaskEnum.magic_level_69,
      TaskEnum.fletching_level_10,
      TaskEnum.woodcutting_level_56,
      TaskEnum.runecraft_level_5,
      TaskEnum.slayer_level_66,
      TaskEnum.farming_level_5,
      TaskEnum.construction_level_20,
      TaskEnum.hunter_level_48,
      TaskEnum.sailing_level_5,
      TaskEnum.contact, TaskEnum.desert_treasure_i, TaskEnum.dream_mentor, TaskEnum.eagles_peak, TaskEnum.enakhras_lament, TaskEnum.the_feud, TaskEnum.the_golem, TaskEnum.spirits_of_the_elid
    ],
  } as Task,
  {
    type: TypeEnum.diary,
    task: TaskEnum.desert_elite,
    requirements: [
      TaskEnum.desert_medium,
      TaskEnum.attack_level_52,
      TaskEnum.hitpoints_level_5,
      TaskEnum.mining_level_60,
      TaskEnum.strength_level_5,
      TaskEnum.agility_level_72,
      TaskEnum.smithing_level_69,
      TaskEnum.defence_level_40,
      TaskEnum.herblore_level_40,
      TaskEnum.fishing_level_5,
      TaskEnum.ranged_level_40,
      TaskEnum.thieving_level_91,
      TaskEnum.cooking_level_85,
      TaskEnum.prayer_level_85,
      TaskEnum.crafting_level_63,
      TaskEnum.firemaking_level_60,
      TaskEnum.magic_level_94,
      TaskEnum.fletching_level_95,
      TaskEnum.woodcutting_level_56,
      TaskEnum.runecraft_level_5,
      TaskEnum.slayer_level_66,
      TaskEnum.farming_level_5,
      TaskEnum.construction_level_79,
      TaskEnum.hunter_level_48,
      TaskEnum.sailing_level_5,
      TaskEnum.contact, TaskEnum.desert_treasure_i, TaskEnum.dream_mentor, TaskEnum.eagles_peak, TaskEnum.enakhras_lament, TaskEnum.the_feud, TaskEnum.the_golem, TaskEnum.spirits_of_the_elid
    ],
  } as Task,

  {
    type: TypeEnum.diary,
    task: TaskEnum.falador_easy,
    requirements: [TaskEnum.mining_level_10, TaskEnum.agility_level_5, TaskEnum.smithing_level_15, TaskEnum.construction_level_20, TaskEnum.dorics_quest, TaskEnum.the_knights_sword],
  } as Task,
  {
    type: TypeEnum.diary,
    task: TaskEnum.falador_medium,
    requirements: [
      TaskEnum.falador_easy,
      TaskEnum.mining_level_40,
      TaskEnum.strength_level_40,
      TaskEnum.agility_level_44,
      TaskEnum.smithing_level_15,
      TaskEnum.defence_level_20,
      TaskEnum.ranged_level_20,
      TaskEnum.thieving_level_40,
      TaskEnum.cooking_level_20,
      TaskEnum.prayer_level_10,
      TaskEnum.crafting_level_40,
      TaskEnum.firemaking_level_52,
      TaskEnum.magic_level_40,
      TaskEnum.fletching_level_5,
      TaskEnum.woodcutting_level_30,
      TaskEnum.slayer_level_35,
      TaskEnum.farming_level_25,
      TaskEnum.construction_level_20,
      TaskEnum.dorics_quest, TaskEnum.the_knights_sword, TaskEnum.recruitment_drive, TaskEnum.skippy_and_the_mogres, TaskEnum.ratcatchers
    ],
    questPointRequirement: 12
  } as Task,
  {
    type: TypeEnum.diary,
    task: TaskEnum.falador_hard,
    requirements: [
      TaskEnum.falador_medium,
      TaskEnum.attack_level_66,
      TaskEnum.hitpoints_level_5,
      TaskEnum.mining_level_60,
      TaskEnum.strength_level_66,
      TaskEnum.agility_level_60,
      TaskEnum.smithing_level_15,
      TaskEnum.defence_level_52,
      TaskEnum.herblore_level_52,
      TaskEnum.fishing_level_56,
      TaskEnum.ranged_level_20,
      TaskEnum.thieving_level_60,
      TaskEnum.cooking_level_56,
      TaskEnum.prayer_level_72,
      TaskEnum.crafting_level_40,
      TaskEnum.firemaking_level_52,
      TaskEnum.magic_level_40,
      TaskEnum.fletching_level_5,
      TaskEnum.woodcutting_level_72,
      TaskEnum.runecraft_level_56,
      TaskEnum.slayer_level_72,
      TaskEnum.farming_level_48,
      TaskEnum.construction_level_20,
      TaskEnum.hunter_level_5,
      TaskEnum.sailing_level_5,
      TaskEnum.dorics_quest, TaskEnum.grim_tales, TaskEnum.heroes_quest, TaskEnum.the_knights_sword, TaskEnum.skippy_and_the_mogres, TaskEnum.the_slug_menace, TaskEnum.ratcatchers
    ],
    questPointRequirement: 55
  } as Task,
  {
    type: TypeEnum.diary,
    task: TaskEnum.falador_elite,
    requirements: [
      TaskEnum.falador_hard,
      TaskEnum.attack_level_66,
      TaskEnum.hitpoints_level_5,
      TaskEnum.mining_level_60,
      TaskEnum.strength_level_66,
      TaskEnum.agility_level_81,
      TaskEnum.smithing_level_15,
      TaskEnum.defence_level_52,
      TaskEnum.herblore_level_83,
      TaskEnum.fishing_level_56,
      TaskEnum.ranged_level_20,
      TaskEnum.thieving_level_60,
      TaskEnum.cooking_level_56,
      TaskEnum.prayer_level_72,
      TaskEnum.crafting_level_40,
      TaskEnum.firemaking_level_52,
      TaskEnum.magic_level_40,
      TaskEnum.fletching_level_5,
      TaskEnum.woodcutting_level_75,
      TaskEnum.runecraft_level_88,
      TaskEnum.slayer_level_72,
      TaskEnum.farming_level_91,
      TaskEnum.construction_level_20,
      TaskEnum.hunter_level_5,
      TaskEnum.sailing_level_5,
      TaskEnum.dorics_quest, TaskEnum.grim_tales, TaskEnum.heroes_quest, TaskEnum.the_knights_sword, TaskEnum.skippy_and_the_mogres, TaskEnum.the_slug_menace, TaskEnum.ratcatchers
    ],
    questPointRequirement: 55
  } as Task,

  {
    type: TypeEnum.diary,
    task: TaskEnum.fremennik_easy,
    requirements: [
      TaskEnum.mining_level_20, TaskEnum.smithing_level_20, TaskEnum.thieving_level_5, TaskEnum.crafting_level_25, TaskEnum.firemaking_level_15, TaskEnum.woodcutting_level_15, TaskEnum.hunter_level_15,
      TaskEnum.the_fremennik_trials, TaskEnum.the_giant_dwarf, TaskEnum.troll_stronghold
    ],
  } as Task,
  {
    type: TypeEnum.diary,
    task: TaskEnum.fremennik_medium,
    requirements: [
      TaskEnum.fremennik_easy,
      TaskEnum.mining_level_40,
      TaskEnum.agility_level_35,
      TaskEnum.smithing_level_52,
      TaskEnum.defence_level_30,
      TaskEnum.thieving_level_44,
      TaskEnum.crafting_level_35,
      TaskEnum.firemaking_level_40,
      TaskEnum.woodcutting_level_52,
      TaskEnum.slayer_level_48,
      TaskEnum.construction_level_40,
      TaskEnum.hunter_level_35,
      TaskEnum.between_a_rock,
      TaskEnum.eagles_peak,
      TaskEnum.horror_from_the_deep,
      TaskEnum.fairytale_ii_cure_a_queen,
      TaskEnum.the_giant_dwarf,
      TaskEnum.troll_stronghold,
      TaskEnum.olafs_quest
    ],
  } as Task,
  {
    type: TypeEnum.diary,
    task: TaskEnum.fremennik_hard,
    requirements: [
      TaskEnum.fremennik_medium,
      TaskEnum.attack_level_5,
      TaskEnum.hitpoints_level_5,
      TaskEnum.mining_level_72,
      TaskEnum.strength_level_5,
      TaskEnum.agility_level_35,
      TaskEnum.smithing_level_60,
      TaskEnum.defence_level_40,
      TaskEnum.herblore_level_66,
      TaskEnum.fishing_level_56,
      TaskEnum.ranged_level_5,
      TaskEnum.thieving_level_75,
      TaskEnum.cooking_level_56,
      TaskEnum.prayer_level_5,
      TaskEnum.crafting_level_63,
      TaskEnum.firemaking_level_52,
      TaskEnum.magic_level_72,
      TaskEnum.fletching_level_5,
      TaskEnum.woodcutting_level_56,
      TaskEnum.runecraft_level_5,
      TaskEnum.slayer_level_48,
      TaskEnum.farming_level_5,
      TaskEnum.construction_level_40,
      TaskEnum.hunter_level_56,
      TaskEnum.sailing_level_5,
      TaskEnum.between_a_rock,
      TaskEnum.eadgars_ruse,
      TaskEnum.eagles_peak,
      TaskEnum.horror_from_the_deep,
      TaskEnum.fairytale_ii_cure_a_queen,
      TaskEnum.the_giant_dwarf,
      TaskEnum.troll_stronghold,
      TaskEnum.olafs_quest,
      TaskEnum.lunar_diplomacy,
      TaskEnum.throne_of_miscellania
    ],
    questPointRequirement: 55
  } as Task,
  {
    type: TypeEnum.diary,
    task: TaskEnum.fremennik_elite,
    requirements: [
      TaskEnum.fremennik_hard,
      TaskEnum.attack_level_5,
      TaskEnum.hitpoints_level_72,
      TaskEnum.mining_level_72,
      TaskEnum.strength_level_72,
      TaskEnum.agility_level_81,
      TaskEnum.smithing_level_60,
      TaskEnum.defence_level_40,
      TaskEnum.herblore_level_66,
      TaskEnum.fishing_level_56,
      TaskEnum.ranged_level_72,
      TaskEnum.thieving_level_75,
      TaskEnum.cooking_level_56,
      TaskEnum.prayer_level_5,
      TaskEnum.crafting_level_81,
      TaskEnum.firemaking_level_52,
      TaskEnum.magic_level_72,
      TaskEnum.fletching_level_5,
      TaskEnum.woodcutting_level_56,
      TaskEnum.runecraft_level_83,
      TaskEnum.slayer_level_83,
      TaskEnum.farming_level_5,
      TaskEnum.construction_level_40,
      TaskEnum.hunter_level_56,
      TaskEnum.sailing_level_5,
      TaskEnum.between_a_rock,
      TaskEnum.eadgars_ruse,
      TaskEnum.eagles_peak,
      TaskEnum.horror_from_the_deep,
      TaskEnum.fairytale_ii_cure_a_queen,
      TaskEnum.the_giant_dwarf,
      TaskEnum.troll_stronghold,
      TaskEnum.olafs_quest,
      TaskEnum.lunar_diplomacy,
      TaskEnum.throne_of_miscellania
    ],
  } as Task,

  {
    type: TypeEnum.diary,
    task: TaskEnum.kandarin_easy,
    requirements: [TaskEnum.agility_level_20, TaskEnum.fishing_level_20, TaskEnum.crafting_level_5, TaskEnum.slayer_level_5, TaskEnum.farming_level_15, TaskEnum.elemental_workshop_i],
  } as Task,
  {
    type: TypeEnum.diary,
    task: TaskEnum.kandarin_medium,
    requirements: [
      TaskEnum.kandarin_easy,
      TaskEnum.mining_level_30, TaskEnum.strength_level_25, TaskEnum.agility_level_40, TaskEnum.smithing_level_30, TaskEnum.herblore_level_40, TaskEnum.fishing_level_48, TaskEnum.ranged_level_40,
      TaskEnum.thieving_level_48, TaskEnum.cooking_level_44, TaskEnum.crafting_level_35, TaskEnum.magic_level_48, TaskEnum.fletching_level_52, TaskEnum.woodcutting_level_40, TaskEnum.slayer_level_5,
      TaskEnum.farming_level_30, TaskEnum.alfred_grimhands_barcrawl, TaskEnum.waterfall_quest, TaskEnum.fairytale_ii_cure_a_queen, TaskEnum.elemental_workshop_ii
    ],
  } as Task,
  {
    type: TypeEnum.diary,
    task: TaskEnum.kandarin_hard,
    requirements: [
      TaskEnum.kandarin_medium,
      TaskEnum.attack_level_20,
      TaskEnum.hitpoints_level_5,
      TaskEnum.mining_level_30,
      TaskEnum.strength_level_52,
      TaskEnum.agility_level_60,
      TaskEnum.smithing_level_75,
      TaskEnum.defence_level_72,
      TaskEnum.herblore_level_48,
      TaskEnum.fishing_level_72,
      TaskEnum.ranged_level_40,
      TaskEnum.thieving_level_56,
      TaskEnum.cooking_level_44,
      TaskEnum.prayer_level_72,
      TaskEnum.crafting_level_35,
      TaskEnum.firemaking_level_66,
      TaskEnum.magic_level_56,
      TaskEnum.fletching_level_72,
      TaskEnum.woodcutting_level_60,
      TaskEnum.runecraft_level_5,
      TaskEnum.slayer_level_5,
      TaskEnum.farming_level_30,
      TaskEnum.construction_level_52,
      TaskEnum.hunter_level_5,
      TaskEnum.sailing_level_5,
      TaskEnum.alfred_grimhands_barcrawl,
      TaskEnum.barbarian_training,
      TaskEnum.desert_treasure_i,
      TaskEnum.fairytale_ii_cure_a_queen,
      TaskEnum.elemental_workshop_ii,
      TaskEnum.knights_waves_training_grounds
    ],
    questPointRequirement: 12
  } as Task,
  {
    type: TypeEnum.diary,
    task: TaskEnum.kandarin_elite,
    requirements: [
      TaskEnum.kandarin_hard,
      TaskEnum.attack_level_20,
      TaskEnum.hitpoints_level_5,
      TaskEnum.mining_level_60,
      TaskEnum.strength_level_52,
      TaskEnum.agility_level_60,
      TaskEnum.smithing_level_90,
      TaskEnum.defence_level_72,
      TaskEnum.herblore_level_86,
      TaskEnum.fishing_level_77,
      TaskEnum.ranged_level_40,
      TaskEnum.thieving_level_56,
      TaskEnum.cooking_level_81,
      TaskEnum.prayer_level_72,
      TaskEnum.crafting_level_85,
      TaskEnum.firemaking_level_85,
      TaskEnum.magic_level_87,
      TaskEnum.fletching_level_72,
      TaskEnum.woodcutting_level_60,
      TaskEnum.runecraft_level_5,
      TaskEnum.slayer_level_5,
      TaskEnum.farming_level_79,
      TaskEnum.construction_level_52,
      TaskEnum.hunter_level_5,
      TaskEnum.sailing_level_5,
      TaskEnum.alfred_grimhands_barcrawl,
      TaskEnum.barbarian_training,
      TaskEnum.desert_treasure_i,
      TaskEnum.fairytale_ii_cure_a_queen,
      TaskEnum.elemental_workshop_ii,
      TaskEnum.knights_waves_training_grounds,
      TaskEnum.family_crest,
      TaskEnum.lunar_diplomacy
    ],
    questPointRequirement: 12
  } as Task,

  {
    type: TypeEnum.diary,
    task: TaskEnum.karamja_easy,
    requirements: [TaskEnum.mining_level_40, TaskEnum.agility_level_15],
  } as Task,
  {
    type: TypeEnum.diary,
    task: TaskEnum.karamja_medium,
    requirements: [
      TaskEnum.karamja_easy, TaskEnum.mining_level_40, TaskEnum.agility_level_35, TaskEnum.herblore_level_5, TaskEnum.fishing_level_66, TaskEnum.cooking_level_20, TaskEnum.crafting_level_20,
      TaskEnum.woodcutting_level_52, TaskEnum.farming_level_30, TaskEnum.hunter_level_44, TaskEnum.the_grand_tree, TaskEnum.shilo_village, TaskEnum.dragon_slayer_i, TaskEnum.tai_bwo_wannai_trio
    ],
    questPointRequirement: 32
  } as Task,
  {
    type: TypeEnum.diary,
    task: TaskEnum.karamja_hard,
    requirements: [
      TaskEnum.karamja_medium,
      TaskEnum.attack_level_5,
      TaskEnum.hitpoints_level_5,
      TaskEnum.mining_level_52,
      TaskEnum.strength_level_52,
      TaskEnum.agility_level_56,
      TaskEnum.smithing_level_40,
      TaskEnum.defence_level_5,
      TaskEnum.herblore_level_25,
      TaskEnum.fishing_level_66,
      TaskEnum.ranged_level_44,
      TaskEnum.thieving_level_52,
      TaskEnum.cooking_level_56,
      TaskEnum.prayer_level_5,
      TaskEnum.crafting_level_52,
      TaskEnum.firemaking_level_5,
      TaskEnum.magic_level_60,
      TaskEnum.fletching_level_5,
      TaskEnum.woodcutting_level_52,
      TaskEnum.runecraft_level_44,
      TaskEnum.slayer_level_52,
      TaskEnum.farming_level_30,
      TaskEnum.construction_level_5,
      TaskEnum.hunter_level_44,
      TaskEnum.sailing_level_5,
      TaskEnum.the_grand_tree,
      TaskEnum.tai_bwo_wannai_trio,
      TaskEnum.legends_quest
    ],
    questPointRequirement: 107
  } as Task,
  {
    type: TypeEnum.diary,
    task: TaskEnum.karamja_elite,
    requirements: [
      TaskEnum.karamja_hard,
      TaskEnum.attack_level_5,
      TaskEnum.hitpoints_level_5,
      TaskEnum.mining_level_52,
      TaskEnum.strength_level_52,
      TaskEnum.agility_level_56,
      TaskEnum.smithing_level_40,
      TaskEnum.defence_level_5,
      TaskEnum.herblore_level_87,
      TaskEnum.fishing_level_66,
      TaskEnum.ranged_level_44,
      TaskEnum.thieving_level_52,
      TaskEnum.cooking_level_56,
      TaskEnum.prayer_level_5,
      TaskEnum.crafting_level_52,
      TaskEnum.firemaking_level_5,
      TaskEnum.magic_level_60,
      TaskEnum.fletching_level_5,
      TaskEnum.woodcutting_level_52,
      TaskEnum.runecraft_level_91,
      TaskEnum.slayer_level_52,
      TaskEnum.farming_level_72,
      TaskEnum.construction_level_5,
      TaskEnum.hunter_level_44,
      TaskEnum.sailing_level_5,
      TaskEnum.the_grand_tree,
      TaskEnum.tai_bwo_wannai_trio,
      TaskEnum.legends_quest
    ],
    questPointRequirement: 107
  } as Task,

  {
    type: TypeEnum.diary,
    task: TaskEnum.kourend_easy,
    requirements: [TaskEnum.mining_level_15, TaskEnum.herblore_level_15, TaskEnum.fishing_level_20, TaskEnum.thieving_level_25, TaskEnum.construction_level_25, TaskEnum.druidic_ritual],
  } as Task,
  {
    type: TypeEnum.diary,
    task: TaskEnum.kourend_medium,
    requirements: [
      TaskEnum.kourend_easy, TaskEnum.mining_level_44, TaskEnum.strength_level_20, TaskEnum.agility_level_52, TaskEnum.herblore_level_15, TaskEnum.fishing_level_44, TaskEnum.thieving_level_25,
      TaskEnum.crafting_level_35, TaskEnum.firemaking_level_52, TaskEnum.woodcutting_level_52, TaskEnum.farming_level_48, TaskEnum.construction_level_30, TaskEnum.hunter_level_56,
      TaskEnum.the_ascent_of_arceuus, TaskEnum.the_depths_of_despair, TaskEnum.the_forsaken_tower, TaskEnum.the_queen_of_thieves, TaskEnum.tale_of_the_righteous, TaskEnum.fairytale_ii_cure_a_queen, TaskEnum.eagles_peak
    ],
  } as Task,
  {
    type: TypeEnum.diary,
    task: TaskEnum.kourend_hard,
    requirements: [
      TaskEnum.kourend_medium,
      TaskEnum.attack_level_5,
      TaskEnum.hitpoints_level_5,
      TaskEnum.mining_level_66,
      TaskEnum.strength_level_20,
      TaskEnum.agility_level_52,
      TaskEnum.smithing_level_72,
      TaskEnum.defence_level_40,
      TaskEnum.herblore_level_35,
      TaskEnum.fishing_level_44,
      TaskEnum.ranged_level_5,
      TaskEnum.thieving_level_52,
      TaskEnum.cooking_level_5,
      TaskEnum.prayer_level_5,
      TaskEnum.crafting_level_63,
      TaskEnum.firemaking_level_52,
      TaskEnum.magic_level_66,
      TaskEnum.fletching_level_30,
      TaskEnum.woodcutting_level_60,
      TaskEnum.runecraft_level_5,
      TaskEnum.slayer_level_63,
      TaskEnum.farming_level_75,
      TaskEnum.construction_level_30,
      TaskEnum.hunter_level_56,
      TaskEnum.sailing_level_5,
      TaskEnum.the_ascent_of_arceuus, TaskEnum.the_depths_of_despair, TaskEnum.the_forsaken_tower, TaskEnum.the_queen_of_thieves, TaskEnum.tale_of_the_righteous, TaskEnum.fairytale_ii_cure_a_queen, TaskEnum.eagles_peak
    ],
  } as Task,
  {
    type: TypeEnum.diary,
    task: TaskEnum.kourend_elite,
    requirements: [
      TaskEnum.kourend_hard,
      TaskEnum.attack_level_5,
      TaskEnum.hitpoints_level_90,
      TaskEnum.mining_level_66,
      TaskEnum.strength_level_20,
      TaskEnum.agility_level_52,
      TaskEnum.smithing_level_72,
      TaskEnum.defence_level_40,
      TaskEnum.herblore_level_35,
      TaskEnum.fishing_level_83,
      TaskEnum.ranged_level_5,
      TaskEnum.thieving_level_52,
      TaskEnum.cooking_level_85,
      TaskEnum.prayer_level_5,
      TaskEnum.crafting_level_63,
      TaskEnum.firemaking_level_52,
      TaskEnum.magic_level_90,
      TaskEnum.fletching_level_40,
      TaskEnum.woodcutting_level_90,
      TaskEnum.runecraft_level_77,
      TaskEnum.slayer_level_95,
      TaskEnum.farming_level_85,
      TaskEnum.construction_level_30,
      TaskEnum.hunter_level_56,
      TaskEnum.sailing_level_5,
      TaskEnum.the_ascent_of_arceuus, TaskEnum.the_depths_of_despair, TaskEnum.the_forsaken_tower, TaskEnum.the_queen_of_thieves, TaskEnum.tale_of_the_righteous, TaskEnum.fairytale_ii_cure_a_queen,
      TaskEnum.eagles_peak
    ],
  } as Task,

  {
    type: TypeEnum.diary,
    task: TaskEnum.lumbridge_easy,
    requirements: [
      TaskEnum.mining_level_15, TaskEnum.fishing_level_15, TaskEnum.firemaking_level_15, TaskEnum.woodcutting_level_15, TaskEnum.runecraft_level_5, TaskEnum.slayer_level_10,
      TaskEnum.cooks_assistant, TaskEnum.rune_mysteries
    ],
  } as Task,
  {
    type: TypeEnum.diary,
    task: TaskEnum.lumbridge_medium,
    requirements: [
      TaskEnum.lumbridge_easy,
      TaskEnum.mining_level_15,
      TaskEnum.strength_level_20,
      TaskEnum.agility_level_20,
      TaskEnum.smithing_level_5,
      TaskEnum.fishing_level_30,
      TaskEnum.ranged_level_52,
      TaskEnum.thieving_level_40,
      TaskEnum.prayer_level_5,
      TaskEnum.crafting_level_40,
      TaskEnum.firemaking_level_15,
      TaskEnum.magic_level_35,
      TaskEnum.fletching_level_5,
      TaskEnum.woodcutting_level_40,
      TaskEnum.runecraft_level_25,
      TaskEnum.slayer_level_20,
      TaskEnum.hunter_level_44,
      TaskEnum.animal_magnetism,
      TaskEnum.cooks_assistant,
      TaskEnum.rune_mysteries,
      TaskEnum.fairytale_ii_cure_a_queen
    ],
  } as Task,
  {
    type: TypeEnum.diary,
    task: TaskEnum.lumbridge_hard,
    requirements: [
      TaskEnum.lumbridge_medium,
      TaskEnum.attack_level_5,
      TaskEnum.hitpoints_level_5,
      TaskEnum.mining_level_52,
      TaskEnum.strength_level_20,
      TaskEnum.agility_level_48,
      TaskEnum.smithing_level_40,
      TaskEnum.defence_level_5,
      TaskEnum.herblore_level_25,
      TaskEnum.fishing_level_56,
      TaskEnum.ranged_level_52,
      TaskEnum.thieving_level_56,
      TaskEnum.cooking_level_72,
      TaskEnum.prayer_level_52,
      TaskEnum.crafting_level_72,
      TaskEnum.firemaking_level_66,
      TaskEnum.magic_level_60,
      TaskEnum.fletching_level_10,
      TaskEnum.woodcutting_level_60,
      TaskEnum.runecraft_level_60,
      TaskEnum.slayer_level_20,
      TaskEnum.farming_level_63,
      TaskEnum.construction_level_5,
      TaskEnum.hunter_level_44,
      TaskEnum.sailing_level_5,
      TaskEnum.animal_magnetism,
      TaskEnum.cooks_assistant,
      TaskEnum.rune_mysteries,
      TaskEnum.fairytale_ii_cure_a_queen,
      TaskEnum.another_slice_of_ham,
      TaskEnum.recipe_for_disaster_finale,
      TaskEnum.tears_of_guthix
    ],
    questPointRequirement: 175
  } as Task,
  {
    type: TypeEnum.diary,
    task: TaskEnum.lumbridge_elite,
    requirements: [
      TaskEnum.lumbridge_hard,
      TaskEnum.attack_level_52,
      TaskEnum.hitpoints_level_52,
      TaskEnum.mining_level_72,
      TaskEnum.strength_level_72,
      TaskEnum.agility_level_72,
      TaskEnum.smithing_level_88,
      TaskEnum.defence_level_66,
      TaskEnum.herblore_level_72,
      TaskEnum.fishing_level_63,
      TaskEnum.ranged_level_72,
      TaskEnum.thieving_level_79,
      TaskEnum.cooking_level_72,
      TaskEnum.prayer_level_52,
      TaskEnum.crafting_level_72,
      TaskEnum.firemaking_level_75,
      TaskEnum.magic_level_75,
      TaskEnum.fletching_level_60,
      TaskEnum.woodcutting_level_75,
      TaskEnum.runecraft_level_77,
      TaskEnum.slayer_level_69,
      TaskEnum.farming_level_72,
      TaskEnum.construction_level_72,
      TaskEnum.hunter_level_72,
      TaskEnum.sailing_level_48,
      TaskEnum.animal_magnetism,
      TaskEnum.cooks_assistant,
      TaskEnum.rune_mysteries,
      TaskEnum.fairytale_ii_cure_a_queen,
      TaskEnum.another_slice_of_ham,
      TaskEnum.recipe_for_disaster_finale,
      TaskEnum.tears_of_guthix,
      TaskEnum.desert_treasure_ii_the_fallen_empire,
      TaskEnum.dragon_slayer_ii,
      TaskEnum.monkey_madness_ii,
      TaskEnum.song_of_the_elves,
      TaskEnum.while_guthix_sleeps
    ],
    questPointRequirement: 332
  } as Task,

  {
    type: TypeEnum.diary,
    task: TaskEnum.morytania_easy,
    requirements: [TaskEnum.cooking_level_15, TaskEnum.crafting_level_15, TaskEnum.slayer_level_15, TaskEnum.farming_level_25, TaskEnum.nature_spirit],
  } as Task,
  {
    type: TypeEnum.diary,
    task: TaskEnum.morytania_medium,
    requirements: [
      TaskEnum.morytania_easy, TaskEnum.mining_level_15, TaskEnum.agility_level_44, TaskEnum.smithing_level_52, TaskEnum.herblore_level_25, TaskEnum.fishing_level_52, TaskEnum.ranged_level_40,
      TaskEnum.cooking_level_40, TaskEnum.prayer_level_48, TaskEnum.crafting_level_48, TaskEnum.magic_level_10, TaskEnum.fletching_level_5, TaskEnum.woodcutting_level_48, TaskEnum.slayer_level_44,
      TaskEnum.farming_level_40, TaskEnum.hunter_level_30, TaskEnum.cabin_fever, TaskEnum.dwarf_cannon, TaskEnum.ghosts_ahoy, TaskEnum.lair_of_tarn_razorlor, TaskEnum.in_aid_of_the_myreque
    ],
  } as Task,
  {
    type: TypeEnum.diary,
    task: TaskEnum.morytania_hard,
    requirements: [
      TaskEnum.morytania_medium,
      TaskEnum.attack_level_20,
      TaskEnum.hitpoints_level_5,
      TaskEnum.mining_level_56,
      TaskEnum.strength_level_5,
      TaskEnum.agility_level_72,
      TaskEnum.smithing_level_52,
      TaskEnum.defence_level_72,
      TaskEnum.herblore_level_25,
      TaskEnum.fishing_level_52,
      TaskEnum.ranged_level_40,
      TaskEnum.thieving_level_56,
      TaskEnum.cooking_level_40,
      TaskEnum.prayer_level_72,
      TaskEnum.crafting_level_48,
      TaskEnum.firemaking_level_52,
      TaskEnum.magic_level_66,
      TaskEnum.fletching_level_10,
      TaskEnum.woodcutting_level_52,
      TaskEnum.runecraft_level_5,
      TaskEnum.slayer_level_60,
      TaskEnum.farming_level_56,
      TaskEnum.construction_level_52,
      TaskEnum.hunter_level_30,
      TaskEnum.sailing_level_5,
      TaskEnum.cabin_fever,
      TaskEnum.dwarf_cannon,
      TaskEnum.ghosts_ahoy,
      TaskEnum.lair_of_tarn_razorlor,
      TaskEnum.in_aid_of_the_myreque,
      TaskEnum.desert_treasure_i,
      TaskEnum.the_great_brain_robbery,
      TaskEnum.knights_waves_training_grounds
    ],
    questPointRequirement: 12
  } as Task,
  {
    type: TypeEnum.diary,
    task: TaskEnum.morytania_elite,
    requirements: [
      TaskEnum.morytania_medium,
      TaskEnum.attack_level_20,
      TaskEnum.hitpoints_level_5,
      TaskEnum.mining_level_60,
      TaskEnum.strength_level_77,
      TaskEnum.agility_level_72,
      TaskEnum.smithing_level_52,
      TaskEnum.defence_level_72,
      TaskEnum.herblore_level_25,
      TaskEnum.fishing_level_96,
      TaskEnum.ranged_level_40,
      TaskEnum.thieving_level_56,
      TaskEnum.cooking_level_40,
      TaskEnum.prayer_level_72,
      TaskEnum.crafting_level_85,
      TaskEnum.firemaking_level_81,
      TaskEnum.magic_level_83,
      TaskEnum.fletching_level_10,
      TaskEnum.woodcutting_level_56,
      TaskEnum.runecraft_level_5,
      TaskEnum.slayer_level_85,
      TaskEnum.farming_level_56,
      TaskEnum.construction_level_52,
      TaskEnum.hunter_level_30,
      TaskEnum.sailing_level_5,
      TaskEnum.cabin_fever,
      TaskEnum.dwarf_cannon,
      TaskEnum.ghosts_ahoy,
      TaskEnum.lair_of_tarn_razorlor,
      TaskEnum.in_aid_of_the_myreque,
      TaskEnum.desert_treasure_i,
      TaskEnum.the_great_brain_robbery,
      TaskEnum.knights_waves_training_grounds,
      TaskEnum.lunar_diplomacy,
      TaskEnum.shades_of_mortton,
      TaskEnum.barbarian_training
    ],
    questPointRequirement: 12
  } as Task,

  {
    type: TypeEnum.diary,
    task: TaskEnum.varrock_easy,
    requirements: [
      TaskEnum.mining_level_15,
      TaskEnum.agility_level_15,
      TaskEnum.fishing_level_20,
      TaskEnum.thieving_level_5,
      TaskEnum.crafting_level_10,
      TaskEnum.runecraft_level_10,
      TaskEnum.rune_mysteries
    ],
  } as Task,
  {
    type: TypeEnum.diary,
    task: TaskEnum.varrock_medium,
    requirements: [
      TaskEnum.varrock_easy,
      TaskEnum.mining_level_15,
      TaskEnum.agility_level_30,
      TaskEnum.herblore_level_10,
      TaskEnum.fishing_level_20,
      TaskEnum.thieving_level_25,
      TaskEnum.crafting_level_40,
      TaskEnum.firemaking_level_40,
      TaskEnum.magic_level_25,
      TaskEnum.runecraft_level_10,
      TaskEnum.farming_level_30,
      TaskEnum.the_dig_site,
      TaskEnum.enlightened_journey,
      TaskEnum.garden_of_tranquillity,
      TaskEnum.gertrudes_cat,
      TaskEnum.rune_mysteries,
      TaskEnum.a_souls_bane,
      TaskEnum.tree_gnome_village
    ],
    questPointRequirement: 32
  } as Task,
  {
    type: TypeEnum.diary,
    task: TaskEnum.varrock_hard,
    requirements: [
      TaskEnum.varrock_medium,
      TaskEnum.attack_level_5,
      TaskEnum.hitpoints_level_5,
      TaskEnum.mining_level_15,
      TaskEnum.strength_level_5,
      TaskEnum.agility_level_52,
      TaskEnum.smithing_level_20,
      TaskEnum.defence_level_5,
      TaskEnum.herblore_level_10,
      TaskEnum.fishing_level_20,
      TaskEnum.ranged_level_40,
      TaskEnum.thieving_level_56,
      TaskEnum.cooking_level_5,
      TaskEnum.prayer_level_52,
      TaskEnum.crafting_level_40,
      TaskEnum.firemaking_level_60,
      TaskEnum.magic_level_56,
      TaskEnum.fletching_level_10,
      TaskEnum.woodcutting_level_60,
      TaskEnum.runecraft_level_10,
      TaskEnum.slayer_level_5,
      TaskEnum.farming_level_69,
      TaskEnum.construction_level_52,
      TaskEnum.hunter_level_66,
      TaskEnum.sailing_level_5,
      TaskEnum.the_dig_site,
      TaskEnum.enlightened_journey,
      TaskEnum.garden_of_tranquillity,
      TaskEnum.gertrudes_cat,
      TaskEnum.rune_mysteries,
      TaskEnum.a_souls_bane,
      TaskEnum.tree_gnome_village,
      TaskEnum.desert_treasure_i,
      TaskEnum.bone_voyage
    ],
    questPointRequirement: 32
  } as Task,
  {
    type: TypeEnum.diary,
    task: TaskEnum.varrock_elite,
    requirements: [
      TaskEnum.varrock_hard,
      TaskEnum.attack_level_5,
      TaskEnum.hitpoints_level_5,
      TaskEnum.mining_level_60,
      TaskEnum.strength_level_5,
      TaskEnum.agility_level_52,
      TaskEnum.smithing_level_89,
      TaskEnum.defence_level_40,
      TaskEnum.herblore_level_90,
      TaskEnum.fishing_level_20,
      TaskEnum.ranged_level_40,
      TaskEnum.thieving_level_56,
      TaskEnum.cooking_level_95,
      TaskEnum.prayer_level_52,
      TaskEnum.crafting_level_63,
      TaskEnum.firemaking_level_60,
      TaskEnum.magic_level_86,
      TaskEnum.fletching_level_81,
      TaskEnum.woodcutting_level_60,
      TaskEnum.runecraft_level_79,
      TaskEnum.slayer_level_5,
      TaskEnum.farming_level_69,
      TaskEnum.construction_level_52,
      TaskEnum.hunter_level_66,
      TaskEnum.sailing_level_5,
      TaskEnum.the_dig_site,
      TaskEnum.enlightened_journey,
      TaskEnum.garden_of_tranquillity,
      TaskEnum.gertrudes_cat,
      TaskEnum.rune_mysteries,
      TaskEnum.a_souls_bane,
      TaskEnum.tree_gnome_village,
      TaskEnum.desert_treasure_i,
      TaskEnum.bone_voyage,
      TaskEnum.dream_mentor
    ],
    questPointRequirement: 32
  } as Task,

  {
    type: TypeEnum.diary,
    task: TaskEnum.western_easy,
    requirements: [
      TaskEnum.mining_level_15,
      TaskEnum.ranged_level_30,
      TaskEnum.cooking_level_30,
      TaskEnum.fletching_level_20,
      TaskEnum.hunter_level_10,
      TaskEnum.big_chompy_bird_hunting,
      TaskEnum.rune_mysteries
    ],
  } as Task,
  {
    type: TypeEnum.diary,
    task: TaskEnum.western_medium,
    requirements: [
      TaskEnum.western_easy,
      TaskEnum.mining_level_40,
      TaskEnum.agility_level_40,
      TaskEnum.smithing_level_30,
      TaskEnum.herblore_level_20,
      TaskEnum.fishing_level_48,
      TaskEnum.ranged_level_30,
      TaskEnum.cooking_level_44,
      TaskEnum.crafting_level_25,
      TaskEnum.firemaking_level_35,
      TaskEnum.magic_level_48,
      TaskEnum.fletching_level_20,
      TaskEnum.woodcutting_level_35,
      TaskEnum.construction_level_5,
      TaskEnum.hunter_level_35,
      TaskEnum.big_chompy_bird_hunting,
      TaskEnum.rune_mysteries,
      TaskEnum.eagles_peak,
      TaskEnum.the_eyes_of_glouphrie,
      TaskEnum.monkey_madness_i,
      TaskEnum.one_small_favour
    ],
  } as Task,
  {
    type: TypeEnum.diary,
    task: TaskEnum.western_hard,
    requirements: [
      TaskEnum.western_medium,
      TaskEnum.attack_level_5,
      TaskEnum.hitpoints_level_5,
      TaskEnum.mining_level_72,
      TaskEnum.strength_level_5,
      TaskEnum.agility_level_56,
      TaskEnum.smithing_level_48,
      TaskEnum.defence_level_5,
      TaskEnum.herblore_level_20,
      TaskEnum.fishing_level_63,
      TaskEnum.ranged_level_72,
      TaskEnum.thieving_level_75,
      TaskEnum.cooking_level_72,
      TaskEnum.prayer_level_5,
      TaskEnum.crafting_level_40,
      TaskEnum.firemaking_level_52,
      TaskEnum.magic_level_66,
      TaskEnum.fletching_level_20,
      TaskEnum.woodcutting_level_52,
      TaskEnum.runecraft_level_5,
      TaskEnum.slayer_level_5,
      TaskEnum.farming_level_69,
      TaskEnum.construction_level_66,
      TaskEnum.hunter_level_69,
      TaskEnum.sailing_level_5,
      TaskEnum.big_chompy_bird_hunting,
      TaskEnum.rune_mysteries,
      TaskEnum.eagles_peak,
      TaskEnum.the_eyes_of_glouphrie,
      TaskEnum.monkey_madness_i,
      TaskEnum.one_small_favour,
      TaskEnum.recipe_for_disaster_king_awowogei,
      TaskEnum.swan_song,
      TaskEnum.mournings_end_part_i
    ],
    questPointRequirement: 100
  } as Task,
  {
    type: TypeEnum.diary,
    task: TaskEnum.western_elite,
    requirements: [
      TaskEnum.western_hard,
      TaskEnum.attack_level_44,
      TaskEnum.hitpoints_level_44,
      TaskEnum.mining_level_72,
      TaskEnum.strength_level_44,
      TaskEnum.agility_level_85,
      TaskEnum.smithing_level_48,
      TaskEnum.defence_level_44,
      TaskEnum.herblore_level_20,
      TaskEnum.fishing_level_63,
      TaskEnum.ranged_level_72,
      TaskEnum.thieving_level_85,
      TaskEnum.cooking_level_72,
      TaskEnum.prayer_level_25,
      TaskEnum.crafting_level_40,
      TaskEnum.firemaking_level_52,
      TaskEnum.magic_level_66,
      TaskEnum.fletching_level_85,
      TaskEnum.woodcutting_level_52,
      TaskEnum.runecraft_level_5,
      TaskEnum.slayer_level_93,
      TaskEnum.farming_level_75,
      TaskEnum.construction_level_66,
      TaskEnum.hunter_level_69,
      TaskEnum.sailing_level_5,
      TaskEnum.big_chompy_bird_hunting,
      TaskEnum.rune_mysteries,
      TaskEnum.eagles_peak,
      TaskEnum.the_eyes_of_glouphrie,
      TaskEnum.monkey_madness_i,
      TaskEnum.one_small_favour,
      TaskEnum.recipe_for_disaster_king_awowogei,
      TaskEnum.swan_song,
      TaskEnum.mournings_end_part_i
    ],
    questPointRequirement: 100
  } as Task,

  {
    type: TypeEnum.diary,
    task: TaskEnum.wilderness_easy,
    requirements: [
      TaskEnum.mining_level_15,
      TaskEnum.agility_level_15,
      TaskEnum.magic_level_25,
      TaskEnum.enter_the_abyss
    ],
  } as Task,
  {
    type: TypeEnum.diary,
    task: TaskEnum.wilderness_medium,
    requirements: [
      TaskEnum.wilderness_easy,
      TaskEnum.mining_level_56,
      TaskEnum.strength_level_5,
      TaskEnum.agility_level_52,
      TaskEnum.smithing_level_52,
      TaskEnum.magic_level_60,
      TaskEnum.woodcutting_level_63,
      TaskEnum.slayer_level_52,
      TaskEnum.enter_the_abyss,
      TaskEnum.between_a_rock
    ],
  } as Task,
  {
    type: TypeEnum.diary,
    task: TaskEnum.wilderness_hard,
    requirements: [
      TaskEnum.wilderness_medium,
      TaskEnum.attack_level_5,
      TaskEnum.hitpoints_level_5,
      TaskEnum.mining_level_56,
      TaskEnum.strength_level_5,
      TaskEnum.agility_level_66,
      TaskEnum.smithing_level_75,
      TaskEnum.defence_level_5,
      TaskEnum.herblore_level_5,
      TaskEnum.fishing_level_56,
      TaskEnum.ranged_level_5,
      TaskEnum.thieving_level_5,
      TaskEnum.cooking_level_5,
      TaskEnum.prayer_level_5,
      TaskEnum.crafting_level_5,
      TaskEnum.firemaking_level_5,
      TaskEnum.magic_level_66,
      TaskEnum.fletching_level_5,
      TaskEnum.woodcutting_level_63,
      TaskEnum.runecraft_level_5,
      TaskEnum.slayer_level_69,
      TaskEnum.farming_level_5,
      TaskEnum.construction_level_5,
      TaskEnum.hunter_level_69,
      TaskEnum.sailing_level_5,
      TaskEnum.death_plateau,
      TaskEnum.enter_the_abyss,
      TaskEnum.mage_arena_i,
      TaskEnum.between_a_rock
    ],
  } as Task,
  {
    type: TypeEnum.diary,
    task: TaskEnum.wilderness_elite,
    requirements: [
      TaskEnum.wilderness_hard,
      TaskEnum.attack_level_5,
      TaskEnum.hitpoints_level_5,
      TaskEnum.mining_level_85,
      TaskEnum.strength_level_5,
      TaskEnum.agility_level_66,
      TaskEnum.smithing_level_90,
      TaskEnum.defence_level_5,
      TaskEnum.herblore_level_10,
      TaskEnum.fishing_level_85,
      TaskEnum.ranged_level_40,
      TaskEnum.thieving_level_85,
      TaskEnum.cooking_level_90,
      TaskEnum.prayer_level_5,
      TaskEnum.crafting_level_5,
      TaskEnum.firemaking_level_75,
      TaskEnum.magic_level_96,
      TaskEnum.fletching_level_10,
      TaskEnum.woodcutting_level_75,
      TaskEnum.runecraft_level_5,
      TaskEnum.slayer_level_83,
      TaskEnum.farming_level_5,
      TaskEnum.construction_level_5,
      TaskEnum.hunter_level_69,
      TaskEnum.sailing_level_5,
      TaskEnum.death_plateau,
      TaskEnum.enter_the_abyss,
      TaskEnum.mage_arena_i,
      TaskEnum.between_a_rock,
      TaskEnum.desert_treasure_i
    ],
  } as Task,

] as Task[]
